wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1655552661
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 17
      4: 3.9.10
      5: 0.12.16
      8:
      - 5
